### ISSUE TITLE
gist.el stopped working: Invalid slot type: gh-gist-gist, id, string, nil

### ISSUE THREAD

**Issue by vmalloc** [defunkt/gist.el#88]
Attempting to post buffers to gist fails with: `byte-code: Invalid slot type: gh-gist-gist, id, string, nil`

Using Emacs 24.5.1, with gist.el 1.3.1

**Comment by incandescentman** [comment]
Same issue here.

**Comment by sigma** [comment]
I just pushed an update to gh.el. can you give it a shot? if that doesn't help, please reopen and post the backtrace you'll get (with `M-x toggle-debug-on-error`)

Thanks

**Comment by vmalloc** [comment]
@sigma after upgrading I get:

```
Debugger entered--Lisp error: (void-function gh-defclass)
  (gh-defclass gh-gist-gist-stub (gh-object) ((files :initarg :files :type list :initform nil :marshal-type (list gh-gist-gist-file)) (public :initarg :public :marshal-type bool) (description :initarg :description)) "Class for user-created gist objects")
  eval-buffer(#<buffer  *load*-38078> nil "/Users/rotemy/.emacs.d/elpa/gh-20160724.1930/gh-autoloads.el" nil t)  ; Reading at buffer position 1724
  load-with-code-conversion("/Users/rotemy/.emacs.d/elpa/gh-20160724.1930/gh-autoloads.el" "/Users/rotemy/.emacs.d/elpa/gh-20160724.1930/gh-autoloads.el" nil t)
  load("/Users/rotemy/.emacs.d/elpa/gh-20160724.1930/gh-autoloads" nil t)
  #[0 "\302\303\304\305\300\"\301\"\306\307#\207" [gh "/Users/rotemy/.emacs.d/elpa/gh-20160724.1930" load expand-file-name format "%s-autoloads" nil t] 5 "\n\n(fn)"]()
  funcall(#[0 "\302\303\304\305\300\"\301\"\306\307#\207" [gh "/Users/rotemy/.emacs.d/elpa/gh-20160724.1930" load expand-file-name format "%s-autoloads" nil t] 5 "\n\n(fn)"])
  package-activate-1([cl-struct-package-desc gh (20160724 1930) "A GitHub library for Emacs" ((emacs (24 3)) (s (1 9 0)) (dash (2 9 0)) (pcache (0 4 1)) (logito (0 1)) (marshal (0 6 1))) nil nil "/Users/rotemy/.emacs.d/elpa/gh-20160724.1930" nil nil])
  package-activate(gh (0 9 2))
  #[0 "\300\302H	>\204\303\304\305\306#\210\300\307H\211\2050\211@\310@\211A@\262\"\204)\311\312\"\210A\266\202\202\207" [[cl-struct-package-desc gist (20160118 1656) "Emacs integration for gist.github.com" ((emacs (24 1)) (gh (0 9 2))) nil nil "/Users/rotemy/.emacs.d/elpa/gist-20160118.1656" ((:keywords "tools") (:url . "https://github.com/defunkt/gist.el")) nil] cl-struct-package-desc-tags 0 error "%s accessing a non-%s" package-desc-reqs package-desc 4 package-activate throw dep-failure] 6 "\n\n(fn)"]()
  funcall(#[0 "\300\302H	>\204\303\304\305\306#\210\300\307H\211\2050\211@\310@\211A@\262\"\204)\311\312\"\210A\266\202\202\207" [[cl-struct-package-desc gist (20160118 1656) "Emacs integration for gist.github.com" ((emacs (24 1)) (gh (0 9 2))) nil nil "/Users/rotemy/.emacs.d/elpa/gist-20160118.1656" ((:keywords "tools") (:url . "https://github.com/defunkt/gist.el")) nil] cl-struct-package-desc-tags 0 error "%s accessing a non-%s" package-desc-reqs package-desc 4 package-activate throw dep-failure] 6 "\n\n(fn)"])
  package-activate(gist)
  package-initialize()
  eval-buffer(#<buffer  *load*-321028> nil "/Users/rotemy/.emacs.d/setup-package.el" nil t)  ; Reading at buffer position 357
  load-with-code-conversion("/Users/rotemy/.emacs.d/setup-package.el" "/Users/rotemy/.emacs.d/setup-package.el" nil nil)
  load("~/.emacs.d/setup-package.el")
  eval-buffer(#<buffer  *load*> nil "/Users/rotemy/.emacs.d/init.el" nil t)  ; Reading at buffer position 563
  load-with-code-conversion("/Users/rotemy/.emacs.d/init.el" "/Users/rotemy/.emacs.d/init.el" t t)
  load("/Users/rotemy/.emacs.d/init" t t)
  #[0 "\205\262	\306=\203\307\310Q\202;	\311=\204\307\312Q\202;\313\307\314\315#\203*\316\202;\313\307\314\317#\203:\320\nB\321\202;\316\322\323\322\211#\210\322=\203a\324\325\326\307\327Q!\"\323\322\211#\210\322=\203`\210\203\243\330!\331\232\203\243\332!\211\333P\334!\203}\211\202\210\334!\203\207\202\210\314\262\203\241\335\"\203\237\336\337#\210\340\341!\210\266\f?\205\260\314\323\342\322\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" (initialization "`_emacs' init file is deprecated, please use `.emacs'") "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7 "\n\n(fn)"]()
  command-line()
  normal-top-level()
```

**Comment by jwiegley** [comment]
This is still happening.  The `gist` object passed to `gist-created-callback` returns `nil` for `(oref gist :html-url)`.
